# Code : Inverted Number Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4
    4444
    333
    22
    1
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints :
    0 <= N <= 50
    Sample Input 1:
    5
    Sample Output 1:
    55555 
    4444
    333
    22
    1
    Sample Input 2:
    6
    Sample Output 2:
    666666
    55555 
    4444
    333
    22
    1

In [ ]:
num = int(input())
i=1
while i<=num:
    j=1
    while j<=num-i+1:
        print(num-i+1,end='')
        j+=1
    print()
    i+=1

# Code : Mirror Number Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4




    The dots represent spaces.


    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 50
    Sample Input 1:
    3
    Sample Output 1:
          1 
         12
        123
    Sample Input 2:
    4
    Sample Output 2:
          1 
         12
        123
       1234

In [ ]:
n = int(input())
i=1
while i<=n:
    s=1
    while s<=n-i:
        print(' ',end='')
        s+=1
    num=1
    while num<=i:
        print(num,end='')
        num+=1
    print()
    i+=1

# Code : Star Pattern
    Print the following pattern
    Pattern for N = 4



    The dots represent spaces.



    Input Format :
    N (Total no. of rows)
    Output Format :
    Pattern in N lines
    Constraints :
    0 <= N <= 50
    Sample Input 1 :
    3
    Sample Output 1 :
       *
      *** 
     *****
    Sample Input 2 :
    4
    Sample Output 2 :
        *
       *** 
      *****
     *******

In [ ]:



n = int(input())

i=1
while i<=n:
    s=1
    while s<=n-i:
        print(' ',end='')
        s+=1
    s1=1
    while s1<=i:
        print('*',end='')
        s1+=1
    s2=i-1
    while s2>=1:
        print('*',end='')
        s2-=1
    
    print()
    i+=1

# Code : Triangle of Numbers

    Print the following pattern for the given number of rows.
    Pattern for N = 4



    The dots represent spaces.



    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints :
    0 <= N <= 50
    Sample Input 1:
    5
    Sample Output 1:
               1
             232
           34543
         4567654
       567898765
    Sample Input 2:
    4
    Sample Output 2:
               1
             232
           34543
         4567654

In [ ]:


n = int(input())

i=1
r=0
while i<=n:
    s=1
    while s<=n-i:
        print(' ',end='')
        s+=1
    s1=1
    k=i
    while s1<=i:
        print(k,end='')
        s1+=1
        k+=1
    s2=i-1
    st=i+r-1
    while s2>=1:
        print(st,end='')
        k-=1
        s2-=1
        st-=1
    r+=1
    print()
    i+=1

# Code : Diamond of stars
    Print the following pattern for the given number of rows.
    Note: N is always odd.


    Pattern for N = 5



    The dots represent spaces.



    Input format :
    N (Total no. of rows and can only be odd)
    Output format :
    Pattern in N lines
    Constraints :
    1 <= N <= 49
    Sample Input 1:
    5
    Sample Output 1:
      *
     ***
    *****
     ***
      *
    Sample Input 2:
    3
    Sample Output 2:
      *
     ***
      *

In [ ]:
n1 = int(input())
n=(n1+1)/2
i=1
k=1
k1=1
while i<=n1:
    if i<=n:
        s=1
        while s<=n-i:
            print(' ',end='')
            s+=1
        s1=1
        while s1<=i:
            print('*',end='')
            s1+=1
        s2=i-1
        while s2>=1:
            print('*',end='')
            s2-=1
    
    if i>n:
        r=1
        while r<=i-n:
            print(' ',end='')
            r+=1
        s=1
        while s<=n-k:
            print('*',end='')
            s+=1
        s1=1
        while s1<=n-k1-1:
            print('*',end='')
            s1+=1
        k1+=1
        k+=1 
    print()
    i+=1

# Number Pattern
    Print the following pattern for n number of rows.
    Note: each line consist of equal number of characters + spaces. Suppose you are printing xth line for N=n. You need to print 1..x followed by (n-x) spaces, again (n-x) spaces followed by x..1
    For eg. N = 5

    1        1
    12      21
    123    321
    1234  4321
    1234554321
    Sample Input 1 :
    4
    Sample Output 1 :
    1      1
    12    21
    123  321
    12344321

In [ ]:
n = int(input())
for i in range(1,n+1):
    for j in range(1,i+1):
        print(j,end='')
    for j in range(0,2*n-2*i):
        print(" ",end='')
    for j in range(i,0,-1):
        print(j,end='')
    print('')

# Zeros and Stars Pattern
    Print the following pattern
    Pattern for N = 4
    *000*000*
    0*00*00*0
    00*0*0*00
    000***000
    Input Format :
    N (Total no. of rows)
    Output Format :
    Pattern in N lines
    Sample Input 1 :
    3
    Sample Output 1 :
    *00*00*
    0*0*0*0
    00***00
    Sample Input 2 :
    5
    Sample Output 2 :
    *0000*0000*
    0*000*000*0
    00*00*00*00
    000*0*0*000
    0000***0000

In [ ]:
n = int(input())
i=1
while i<=n:
    j=1
    while j<=n*2+1:
        if i==j or j==n+1 or j==n*2+2-i:
            print("*",end='')
        else:
            print(0,end='')
        j+=1
    print()
    i+=1

# Pyramid Number Pattern
    Print the following pattern for the given number of rows.
    Pattern for N = 4
       1
      212
     32123
    4321234
    Input format : N (Total no. of rows)

    Output format : Pattern in N lines

    Sample Input :
    5
    Sample Output :
            1
          212
        32123
      4321234
    543212345

In [ ]:
n = int(input())

i=1
while i<=n:
    j=1
    k=i
    while j<=n*2-1:
        if n+1-i<= j and j<=n-1+i:
            if j<=n: 
                    print(k,end='')
                    k-=1
            else:
                k+=1
                print(k+1,end='')
                
        else:
            print(' ',end='')
        j+=1
    print()
    i+=1

# Arrow pattern

    Print the following pattern for the given number of rows.
    Assume N is always odd.
    Note : There is space after every star.
    Pattern for N = 7
    *
     * *
       * * *
         * * * *
       * * *
     * *
    *
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Sample Input :
    11
    Sample Output :
    *
     * *
       * * *
         * * * *
           * * * * *
             * * * * * *
           * * * * *
         * * * *
       * * *
     * *
    *

In [ ]:
n = int(input())
i=1
k=(n-1)//2
flag=0
while i<=n:
    j=1
    while j<=n:
        if i<=(n+1)//2:
            if i<=j and j<=i*2-1:
                print('* ',end='')
            
            elif j>=i*2-1:
                pass
            else:
                   print(' ',end='') 
        else:
            flag=1
            if n+1-i<=j and j<=k*2-1:
                     print('* ',end='')  
           
            elif j>=k*2-1:
                pass
            else:
                print(' ',end='')
        j+=1
    print()
    i+=1
    if flag==1:
        k-=1