# Binary Pattern
    Print the following pattern for the given number of rows.
    Pattern for N = 4
    1111
    000
    11
    0
    Input format : N (Total no. of rows)

    Output format : Pattern in N lines

    Sample Input :
    5
    Sample Output :
    11111
    0000
    111
    00
    11

In [ ]:
n = int(input())

for i in range(1,n+1):
    for j in range(1,n-i+2):
        print(1 if i%2!=0 else 0,end='')
    print()

# Print Number Pyramid
    Print the following pattern for a given n.
    For eg. N = 6
    123456
      23456
        3456
          456
            56
              6
            56
          456
        3456
      23456
    123456
    Sample Input 1 :
    4
    Sample Output 1 :
    1234
      234
        34
          4
        34
      234
    123456

In [ ]:
n = int(input())
for i in range(1,n*2):

    for j in range(1,n+1):
        if i<=n*2//2:
            if i<=j:
                print(j,end='')
            else:
                print(' ',end='')
        else:
            if n*2-i<=j:
                print(j,end='')
            else:
                print(' ',end='')
    print()

# Diamond of Stars
    Print the following pattern for the given number of rows.
    Note: N is always odd.


    Pattern for N = 5



    The dots represent spaces.



    Input format :
    N (Total no. of rows and can only be odd)
    Output format :
    Pattern in N lines
    Constraints :
    1 <= N <= 49
    Sample Input 1:
    5
    Sample Output 1:
      *
     ***
    *****
     ***
      *
    Sample Input 2:
    3
    Sample Output 2:
      *
     ***
      *

In [ ]:
n = int(input())
k=1
for i in range(1,n+1):
    if i<=(n+1)//2:
        for j in range(1,((n+1)//2)+i):
           
            if ((n+1)//2)+1-i<=j:
                print('*',end='')
            else:
                print(' ',end='')
    else:
        for o in range(1,n-k+1):
            if k+1<=o:
                print('*',end='')
            else:
                print(' ',end='')
    
        k+=1
    print()

# Rectangular numbers
    Print the following pattern for the given number of rows.
    Pattern for N = 4
    4444444
    4333334
    4322234
    4321234
    4322234
    4333334  
    4444444
    Input format : N (Total no. of rows)

    Output format : Pattern in N lines

    Sample Input :
    3
    Sample Output :
    33333
    32223
    32123
    32223
    33333

In [ ]:
def prints(a, size): 
    for i in range(size): 
        for j in range(size):
            print(a[i][j], end = '')
        print() 
n = int(input())
size = 2 * n - 1
front = 0
back = size - 1
a = [[0 for i in range(size)]  for i in range(size)]
while (n != 0): 
    for i in range(front, back + 1):
        for j in range(front, back + 1):
            if (i == front or i == back or
                j == front or j == back):
                a[i][j] = n
    front += 1
    back -= 1
    n -= 1
prints(a,size)

# Print the pattern
    Print the following pattern for the given number of rows.
    Pattern for N = 5
     1    2   3    4   5
     11   12  13   14  15
     21   22  23   24  25
     16   17  18   19  20
     6    7    8   9   10
    Input format : N (Total no. of rows)

    Output format : Pattern in N lines

    Sample Input :
    4
    Sample Output :
     1  2  3  4
     9 10 11 12
    13 14 15 16
     5  6  7  8

In [ ]:
n=int(input())

a=[[0 for i in range(n)] for i in range(n)]
m=1
for i in range((n-1)//2+1):
    for k in range(2):
        for j in range(n):
            
            if k==0:
                a[i][j]=m
             
            elif n%2!=0 and i!=(n-1)//2 and k==1:
              
                a[n-1-i][j]=m
            elif n%2==0 and k==1:
                a[n-1-i][j]=m
            m+=1
            
for i in a:
    for j in i:
        print(j,end=' ')
    print()